import ten from "@/assets/images/Mens/ten.jpg";
import three from "@/assets/images/Mens/three.jpg";
import eleven from "@/assets/images/Mens/eleven.jpg";
import eight from "@/assets/images/Mens/eight.jpg";
import two from "@/assets/images/Mens/two.jpg";
import fivee from "@/assets/images/Mens/fivee.jpg";
import four from "@/assets/images/Mens/four.jpg";
import six from "@/assets/images/Mens/six.jpg";
import { ProductAttributes } from "./types/products.types";

export const products: ProductAttributes[] = [
  {
    id: "1",
    name: "Classic Blue Plaid Shirt",
    price: 49.9,
    discount: 10.0,
    images: [
      {
        image: ten,
        imageDescription: "Man wearing a blue and white checkered shirt.",
      },
      { image: three, imageDescription: "Detail of the plaid fabric." },
      { image: eleven, imageDescription: "Side view of the blue shirt." },
      { image: eight, imageDescription: "Close-up of the buttons." },
    ],
    description:
      "Camisa xadrez clássica em tons de azul, ideal para um visual casual refinado.",
    sku: "CBPS-001",
    rating: 5,
    reviewsCount: 15,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "2",
    name: "Denim Overlight Jacket",
    price: 89.0,
    images: [
      {
        image: three,
        imageDescription: "Light blue denim jacket over a white tee.",
      },
      { image: ten, imageDescription: "Outdoor shot with denim jacket." },
      { image: six, imageDescription: "Back view of the jacket." },
      { image: two, imageDescription: "Detail of the denim wash." },
    ],
    description:
      "Jaqueta jeans leve de lavagem clara, perfeita para sobreposições.",
    sku: "DOJ-002",
    rating: 4,
    reviewsCount: 8,
    sizes: ["M", "L", "XL"],
  },
  {
    id: "3",
    name: "Salmon Textured Long Sleeve",
    price: 35.5,
    discount: 5.0,
    images: [
      {
        image: eleven,
        imageDescription: "Salmon colored textured long sleeve shirt.",
      },
      {
        image: fivee,
        imageDescription: "Texture detail of the salmon fabric.",
      },
      { image: four, imageDescription: "Man sitting in salmon shirt." },
      { image: eight, imageDescription: "Collar detail." },
    ],
    description:
      "Manga longa com textura diferenciada na cor salmão, estilo e conforto.",
    sku: "STLS-003",
    rating: 4,
    reviewsCount: 12,
    sizes: ["S", "M", "L"],
  },
  {
    id: "4",
    name: "Red Buffalo Check Shirt",
    price: 55.0,
    discount: 15.0,
    images: [
      {
        image: eight,
        imageDescription: "Red and black checkered flannel shirt.",
      },
      { image: ten, imageDescription: "Detail of the buffalo check pattern." },
      { image: three, imageDescription: "Model posing with the red shirt." },
      { image: eleven, imageDescription: "Studio shot of the flannel." },
    ],
    description: "A icônica estampa Buffalo Check em vermelho e preto.",
    sku: "RBCS-004",
    rating: 5,
    reviewsCount: 20,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "5",
    name: "Nude Slim Fit Blazer",
    price: 129.99,
    images: [
      { image: two, imageDescription: "Nude blazer with pink sunglasses." },
      { image: six, imageDescription: "Close-up of the blazer lapel." },
      { image: ten, imageDescription: "Full body shot with the blazer." },
      { image: three, imageDescription: "Shoulder fit detail." },
    ],
    description: "Blazer slim fit em tom nude para eventos sociais modernos.",
    sku: "NSFB-005",
    rating: 5,
    reviewsCount: 6,
    sizes: ["M", "L", "XL"],
  },
  {
    id: "6",
    name: "Just Culture Lavender Tee",
    price: 29.9,
    images: [
      { image: fivee, imageDescription: "Lavender t-shirt with central logo." },
      { image: four, imageDescription: "Graphic detail on the chest." },
      { image: six, imageDescription: "Back view of the tee." },
      { image: eleven, imageDescription: "Close-up of the cotton texture." },
    ],
    description: "Camiseta lavanda em algodão premium com estampa minimalista.",
    sku: "JCLT-006",
    rating: 4,
    reviewsCount: 25,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "7",
    name: "Essential Emerald Sweatshirt",
    price: 45.0,
    discount: 38.3,
    images: [
      { image: four, imageDescription: "Emerald green crewneck sweatshirt." },
      { image: fivee, imageDescription: "Ribbed cuff detail." },
      {
        image: eight,
        imageDescription: "Man wearing the sweatshirt casually.",
      },
      { image: ten, imageDescription: "Close-up of the emerald color." },
    ],
    description: "Moletom gola careca na cor verde esmeralda.",
    sku: "EES-007",
    rating: 4,
    reviewsCount: 18,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "8",
    name: "Basic White Oversized Tee",
    price: 25.0,
    images: [
      {
        image: six,
        imageDescription: "Oversized white t-shirt and sunglasses.",
      },
      { image: two, imageDescription: "Sleeve fit detail." },
      { image: three, imageDescription: "Model in urban setting." },
      { image: fivee, imageDescription: "Premium cotton texture." },
    ],
    description: "Camiseta branca oversized com corte moderno.",
    sku: "BWOT-008",
    rating: 5,
    reviewsCount: 42,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "9",
    name: "Urban Charcoal Hoodie",
    price: 59.9,
    discount: 10.0,
    images: [
      { image: four, imageDescription: "Charcoal grey hoodie close-up." },
      { image: eight, imageDescription: "Model wearing the hoodie." },
      { image: ten, imageDescription: "Detail of the hood." },
      { image: eleven, imageDescription: "Side profile of the hoodie." },
    ],
    description: "Moletom com capuz cinza chumbo, modelagem urbana.",
    sku: "UCH-009",
    rating: 4,
    reviewsCount: 14,
    sizes: ["M", "L", "XL"],
  },
  {
    id: "10",
    name: "Summer Linen Beige Shirt",
    price: 42.0,
    images: [
      { image: two, imageDescription: "Beige linen shirt for summer." },
      { image: six, imageDescription: "Linen fabric detail." },
      { image: three, imageDescription: "Open shirt style." },
      { image: ten, imageDescription: "Model at the beach style." },
    ],
    description: "Camisa de linho respirável, perfeita para climas quentes.",
    sku: "SLBS-010",
    rating: 5,
    reviewsCount: 9,
    sizes: ["S", "M", "L"],
  },
  {
    id: "11",
    name: "Vintage Indigo Denim",
    price: 95.0,
    discount: 20.0,
    images: [
      { image: three, imageDescription: "Vintage washed indigo denim jacket." },
      { image: ten, imageDescription: "Detail of the indigo wash." },
      { image: eight, imageDescription: "Inside pocket detail." },
      { image: six, imageDescription: "Full jacket view." },
    ],
    description: "Jaqueta jeans com lavagem vintage índigo.",
    sku: "VID-011",
    rating: 4,
    reviewsCount: 11,
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "12",
    name: "Pastel Pink Cotton Tee",
    price: 22.5,
    images: [
      {
        image: six,
        imageDescription: "Soft pastel pink premium cotton t-shirt.",
      },
      { image: fivee, imageDescription: "Pink cotton texture." },
      { image: four, imageDescription: "Model in pink tee." },
      { image: two, imageDescription: "Back of the t-shirt." },
    ],
    description: "Camiseta de algodão em tom rosa pastel, leveza total.",
    sku: "PPCT-012",
    rating: 4,
    reviewsCount: 30,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "13",
    name: "Midnight Navy Polo",
    price: 38.0,
    images: [
      { image: ten, imageDescription: "Navy blue polo shirt with white trim." },
      { image: three, imageDescription: "Collar detail on the polo." },
      { image: eleven, imageDescription: "Sleeve trim detail." },
      { image: eight, imageDescription: "Model posing with navy polo." },
    ],
    description: "Camisa polo azul marinho com detalhes contrastantes.",
    sku: "MNP-013",
    rating: 4,
    reviewsCount: 22,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "14",
    name: "Autumn Rust Cardigan",
    price: 65.0,
    discount: 12.0,
    images: [
      { image: eleven, imageDescription: "Rust-colored knit cardigan." },
      { image: four, imageDescription: "Knit pattern detail." },
      { image: fivee, imageDescription: "Close-up of the rust color." },
      { image: ten, imageDescription: "Man wearing cardigan over tee." },
    ],
    description: "Cardigan de tricô na cor ferrugem, sofisticação de outono.",
    sku: "ARC-014",
    rating: 5,
    reviewsCount: 7,
    sizes: ["M", "L", "XL"],
  },
  {
    id: "15",
    name: "Street Style Graphic Tee",
    price: 32.9,
    images: [
      { image: fivee, imageDescription: "Graphic tee with urban art." },
      { image: six, imageDescription: "Detail of the graphic print." },
      { image: four, imageDescription: "Streetwear look with graphic tee." },
      { image: eleven, imageDescription: "Side view of the shirt." },
    ],
    description: "Camiseta com estampa gráfica inspirada na arte urbana.",
    sku: "SSGT-015",
    rating: 4,
    reviewsCount: 19,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "16",
    name: "Premium Black Blazer",
    price: 149.0,
    images: [
      { image: two, imageDescription: "Formal slim-fit black blazer." },
      { image: ten, imageDescription: "Detail of the black fabric." },
      { image: three, imageDescription: "Inside lining detail." },
      { image: eight, imageDescription: "Full formal look." },
    ],
    description: "Blazer preto premium com corte de alfaiataria slim.",
    sku: "PBB-016",
    rating: 5,
    reviewsCount: 5,
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: "17",
    name: "Classic Flannel Green",
    price: 48.5,
    discount: 8.0,
    images: [
      {
        image: eight,
        imageDescription: "Green and black flannel checkered shirt.",
      },
      { image: ten, imageDescription: "Flannel fabric close-up." },
      { image: eleven, imageDescription: "Model in studio with flannel." },
      { image: four, imageDescription: "Back view of the shirt." },
    ],
    description: "Camisa de flanela xadrez verde, robusta e confortável.",
    sku: "CFG-017",
    rating: 4,
    reviewsCount: 16,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "18",
    name: "Desert Sand Long Sleeve",
    price: 39.9,
    images: [
      {
        image: eleven,
        imageDescription: "Sand-colored lightweight long sleeve.",
      },
      { image: fivee, imageDescription: "Fabric detail in sand color." },
      { image: six, imageDescription: "Model walking in sand shirt." },
      { image: two, imageDescription: "Collar detail." },
    ],
    description: "Camisa manga longa na cor areia, versatilidade total.",
    sku: "DSLS-018",
    rating: 4,
    reviewsCount: 13,
    sizes: ["S", "M", "L"],
  },
  {
    id: "19",
    name: "Ocean Blue Crewneck",
    price: 44.0,
    discount: 10.0,
    images: [
      { image: four, imageDescription: "Deep ocean blue crewneck sweatshirt." },
      { image: fivee, imageDescription: "Soft interior detail." },
      { image: eight, imageDescription: "Man relaxing in blue sweatshirt." },
      { image: eleven, imageDescription: "Close-up of the ocean blue shade." },
    ],
    description: "Moletom gola careca azul oceano, conforto garantido.",
    sku: "OBC-019",
    rating: 5,
    reviewsCount: 21,
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "20",
    name: "Minimalist Grey Tee",
    price: 19.99,
    images: [
      { image: six, imageDescription: "Heather grey minimalist t-shirt." },
      { image: two, imageDescription: "Grey cotton texture detail." },
      { image: ten, imageDescription: "Basic look with grey tee." },
      { image: three, imageDescription: "Back view." },
    ],
    description: "Camiseta cinza mescla minimalista, a peça básica essencial.",
    sku: "MGT-020",
    rating: 4,
    reviewsCount: 35,
    sizes: ["S", "M", "L", "XL"],
  },
];
